<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <LangVersion>8</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <HarmonySourcePath>$(MSBuildThisFileDirectory)..\BepInEx\submodules\BepInEx.Harmony\HarmonyXInterop</HarmonySourcePath>
    <Version>1.0.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(HarmonySourcePath)\**\*.cs" Exclude="$(HarmonySourcePath)\bin\**;$(HarmonySourcePath)\obj\**" />
    <PackageReference Include="HarmonyX" Version="2.9.0" />
    <PackageReference Include="Mono.Cecil" Version="0.10.4" />
    <PackageReference Include="MonoMod.RuntimeDetour" Version="22.1.29.1" />
    <PackageReference Include="MonoMod.Utils" Version="22.1.29.1" />
  </ItemGroup>
</Project>
